config/routes.rb
Rails.application.routes.draw do
  get 'login/login'

  get 'login/logout'

  get 'login/alterar_senha'

  resources :users

  root 'login#login'

end

app/models/user.rb
class User < ActiveRecord::Base
  auditable
  acts_as_paranoid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   def current_user
    session[:code_user] = 123
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    render text: "teste"
  end

  def logout
  end

  def alterar_senha
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :nome, :email, :password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjetoExemplo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ProjetoExemplo</a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/login/alterar_senha.html.erb
<h1>Login#alterar_senha</h1>
<p>Find me in app/views/login/alterar_senha.html.erb</p>

app/views/login/login.html.erb
<h1>Login#login</h1>
<p>Find me in app/views/login/login.html.erb</p>

app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :login, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :login, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :admin, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :admin, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deleted_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :deleted_at, :class => 'form-control' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:login) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.login %></td>
        <td><%= user.nome %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%= user.deleted_at %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:login) %>:</strong></dt>
  <dd><%= @user.login %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @user.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:admin) %>:</strong></dt>
  <dd><%= @user.admin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deleted_at) %>:</strong></dt>
  <dd><%= @user.deleted_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>